const assert=require('node:assert/strict'),fs=require('node:fs');
const u=require('../update.js'),v=require('../version.json');
// Frozen code from the shipped v60 HTML, so this checks real old-client behavior.
const legacy=require('./fixtures/update-v60.cjs');
assert.equal(u.compare('V46','51-3'),-1);
assert.equal(u.compare('51-3','51-3'),0);
assert.equal(u.compare('51-10','51-3'),1);
assert.equal(u.compare('51.3.0','51-3'),0);
assert.equal(u.compare('0.9.0','0.10.0'),-1);
assert.throws(()=>u.compare('garbage','0.9.0'));
assert.equal(u.resolve(v).comparison,0);
assert.equal(u.resolve(v).current,'0.9.0');
assert.equal(u.resolve(v).latest,'0.9.0');
const newer={...v,publicVersion:'0.9.1'};
assert.equal(u.resolve(newer).comparison,1);
assert.equal(u.resolve({...v,publicVersion:'0.8.9'}).comparison,-1);
assert.throws(()=>u.resolve({...v,publicVersion:'garbage'}));
assert.throws(()=>u.resolve({...newer,downloadUrl:'javascript:alert(1)'}));
assert.equal(legacy.resolve(v).comparison,1);
assert.equal(legacy.resolve(v).downloadUrl,v.downloadUrl);
assert.equal(legacy.resolve(v,{versionCode:600001,versionName:'60.0-test.1'}).comparison,1);
const oldManifest={...v,version:'60'};delete oldManifest.publicVersion;
assert.equal(u.resolve(oldManifest).comparison,-1);
assert.equal(u.resolve(v,{versionCode:v.android.versionCode,versionName:v.android.versionName}).comparison,0);
assert.equal(u.resolve(v,{versionCode:600001,versionName:'60.0-test.1'}).downloadUrl,v.android.downloadUrl);
assert.equal(u.resolve(v,{versionCode:600003,versionName:'newer'}).comparison,-1);
assert.throws(()=>u.resolve({...v,android:null},{versionCode:1}));
assert.match(fs.readFileSync('index.html','utf8'),/<title>QasDM v0\.9\.0<\/title>/);
assert.equal(v.publicVersion,u.CURRENT_VERSION);
assert.equal(v.version,u.CURRENT_LEGACY_VERSION);
assert.equal(v.developmentVersion,'60');
assert.equal(v.channel,'public-test');
assert.equal(v.releaseTag,'v'+v.publicVersion);
assert.equal(v.android.versionName,v.publicVersion);
assert.match(v.downloadUrl,/\/v0\.9\.0\/QasDM_v0\.9\.0\.html$/);
assert.match(v.android.downloadUrl,/\/v0\.9\.0\/QasDM-0\.9\.0\.apk$/);
assert.match(fs.readFileSync('android-runtime.js','utf8'),/versionCode:600002,versionName:'0\.9\.0'/);
(async()=>{
 assert.equal((await u.check(async()=>({ok:true,json:async()=>v}))).comparison,0);
 await assert.rejects(u.check(async()=>({ok:false,status:503})),/503/);
 await assert.rejects(u.check(async()=>({ok:true,json:async()=>{throw Error('Invalid JSON')}})),/Invalid JSON/);
 let attempts=0;
 const fallback=await u.check(async()=>{if(++attempts===1)throw Error('Failed to fetch');return {ok:true,json:async()=>({encoding:'base64',content:Buffer.from(JSON.stringify(v)).toString('base64')})}});
 assert.equal(attempts,2);assert.equal(fallback.notes,v.notes);
 console.log('PASS public semantic versions, v60 HTML/APK upgrade migration, platform downloads, validation, HTTP/JSON errors and packaged version consistency');
})().catch(e=>{console.error(e);process.exitCode=1});
