const fs=require('node:fs');
module.exports=async function(page,assert,results){
 const shot=async(name)=>{await page.waitForTimeout(270);await page.screenshot({path:'ui-review/'+name+'.png',fullPage:false})};
 const closePages=()=>{for(const p of [...test59.pages])test59.close(p)};
 await page.setViewportSize({width:430,height:900});
 await page.evaluate(()=>{test52.state.shared.listTheme='light';test52.openConversation(test52.active().id);test52.beginSettings();test58.category('identity')});
 await page.waitForTimeout(260);
 const insets=await page.evaluate(()=>[...document.querySelectorAll('#setting-identity58 .settings-form-card59>.field')].map(f=>{const b=f.getBoundingClientRect(),label=f.querySelector('.setting-label59')?.getBoundingClientRect(),control=f.querySelector('input:not([type=checkbox]):not([type=file]):not([type=range]),textarea')?.getBoundingClientRect();return {padding:parseFloat(getComputedStyle(f).paddingLeft),gap:label&&control?control.top-label.bottom:null,line:parseFloat(getComputedStyle(f).lineHeight)}}));
 assert.ok(insets.length>8);assert.ok(insets.every(x=>x.padding>=16&&x.line>=21));assert.ok(insets.filter(x=>x.gap!==null).every(x=>x.gap>=8),'field labels need space above inputs');await shot('v59-phone-identity');
 await page.evaluate(()=>test58.category('tools'));assert.equal(await page.locator('#setting-tools58 hr').count(),0);
 const ownership=await page.evaluate(()=>{const field=id=>document.querySelector('#'+id)?.closest('.field');return {read:field('cfgCrossChat').textContent,memory:field('cfgCrossMemory56').textContent,limit:field('cfgRoleChatLimit').textContent,groups:document.querySelector('#crossGroups13').closest('.settings-cluster59').querySelector('h3').textContent,sms:document.querySelector('#cfgSmsUnknownAllowed').closest('.settings-cluster59').querySelector('h3').textContent}});
 assert.match(ownership.read,/开启后/);assert.match(ownership.memory,/隐藏名单/);assert.match(ownership.limit,/合计计数/);assert.equal(ownership.groups,'跨对话访问');assert.equal(ownership.sms,'模拟短信');await shot('v59-phone-permissions');
 await page.evaluate(()=>{window.draftBeforeDiary59=document.querySelector('#cfgName').value;document.querySelector('#cfgName').value='日记返回后的设置草稿';test58.category('memory');test52.openDiary()});
 assert.ok(await page.evaluate(()=>{const diary=document.querySelector('#diaryOverlay'),settings=document.querySelector('#settingsShade');return parseInt(getComputedStyle(diary).zIndex)>parseInt(getComputedStyle(settings).zIndex)}));
 await page.locator('#diaryBack').click();assert.ok(await page.locator('#settingsShade').evaluate(e=>e.classList.contains('open')));await page.waitForTimeout(220);assert.equal(await page.locator('#diaryOverlay').isVisible(),false);assert.ok(await page.locator('#setting-memory58').isVisible());assert.equal(await page.locator('#cfgName').inputValue(),'日记返回后的设置草稿');
 await page.evaluate(()=>test52.discard());results.push('v59 form insets, help ownership, no obsolete dividers, nested diary returns to live settings');

 await page.evaluate(()=>{test52.state.shared.listTheme='dark';test52.openAppSettings();test59.search()});await shot('v59-dark-search');
 const full=await page.locator('.page57:not([data-closing59])').boundingBox();assert.ok(Math.abs(full.width-430)<2&&full.height>=899);
 const colors=await page.locator('.page-footer59 button').first().evaluate(b=>({bg:getComputedStyle(b).backgroundColor,text:getComputedStyle(b).color}));assert.notEqual(colors.bg,colors.text);assert.notEqual(colors.bg,'rgb(255, 255, 255)');await page.evaluate(closePages);await page.waitForTimeout(210);
 await page.evaluate(()=>{test52.beginSettings();test58.category('developer','global')});await shot('v59-dark-developer');assert.equal(await page.locator('#setting-developer58 hr').count(),0);await page.evaluate(()=>test52.discard());
 await page.evaluate(()=>{test52.openAppSettings();test59.connections()});assert.ok(await page.locator('.page57:not([data-closing59])').textContent().then(t=>t.includes('供应商预设')&&t.includes('DeepSeek')));
 await page.route('https://provider59.example/v1/models',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({data:[{id:'model-a59'},{id:'model-b59'}]})}));
 await page.getByRole('button',{name:'新增供应商',exact:true}).click();const editor=page.locator('.page57:not([data-closing59])').last();
 await editor.locator('input').nth(0).fill('我的第二个供应商');await editor.locator('input').nth(1).fill('https://provider59.example/v1/chat/completions');await editor.locator('input[type=password]').fill('key59');await editor.getByRole('button',{name:'获取模型列表',exact:true}).click();await editor.getByText('获取了 2 个模型；仍可手动填写。',{exact:true}).waitFor();await editor.locator('select').last().selectOption('model-b59');await editor.getByRole('button',{name:'保存',exact:true}).click();
 await page.waitForTimeout(220);assert.ok(await page.evaluate(()=>test52.state.shared.connections56.some(c=>c.name==='我的第二个供应商'&&c.model==='model-b59'&&c.key==='key59')));assert.ok(await page.locator('.connection-card59').textContent().catch(()=>page.locator('.connection-card59').allTextContents()).then(x=>String(x).includes('我的第二个供应商')));await shot('v59-connections');await page.evaluate(closePages);await page.waitForTimeout(210);
 results.push('v59 fullscreen dark search/developer and named multiple connections with fetched/manual model IDs');

 let request;await page.route('https://image59.example/prompt/**',async route=>{request=route.request();await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')})});
 await page.evaluate(async()=>{test52.state.shared.image57={provider:'template',url:'https://image59.example/prompt/{prompt}',key:'should-not-send',connectionId:'',model:''};await test57.generate(test52.active(),{prompt:'雨 / 蓝色 ?'})});assert.equal(request.method(),'GET');assert.ok(request.url().includes(encodeURIComponent('雨 / 蓝色 ?')));assert.equal(request.headers().authorization,undefined);
 await page.evaluate(()=>{test59.image();test59.popup('这是一个很长的确认说明。'.repeat(5))});await shot('v59-dark-popup');assert.equal(await page.locator('#dialog').evaluate(e=>getComputedStyle(e).borderRadius),'26px');await page.evaluate(()=>test52.hideDialog());await page.evaluate(closePages);await page.waitForTimeout(210);results.push('v59 direct encoded image GET without chat key and supplied popup anatomy');

 await page.evaluate(()=>{test52.state.shared.listTheme='light';test52.openAppSettings();test59.background('home')});
 const bg=page.locator('.page57:not([data-closing59])').last();await bg.locator('input[type=range]').nth(0).evaluate(el=>{el.value='40';el.dispatchEvent(new Event('input',{bubbles:true}))});await bg.locator('input[type=range]').nth(1).evaluate(el=>{el.value='7';el.dispatchEvent(new Event('input',{bubbles:true}))});await shot('v59-background');await bg.getByRole('button',{name:'保存',exact:true}).click();await page.waitForTimeout(210);
 assert.deepEqual(await page.evaluate(()=>({opacity:test52.state.shared.backgrounds59.home.opacity,blur:test52.state.shared.backgrounds59.home.blur})),{opacity:.4,blur:7});
 await page.evaluate(()=>test59.background('home'));await page.locator('.page57:not([data-closing59])').last().locator('input[type=range]').nth(0).evaluate(el=>{el.value='10';el.dispatchEvent(new Event('input',{bubbles:true}))});await page.evaluate(()=>test52.back());assert.equal(await page.evaluate(()=>test52.state.shared.backgrounds59.home.opacity),.4);await page.waitForTimeout(210);
 assert.equal(await page.evaluate(()=>test59.backgrounds().length),6);await page.evaluate(()=>{document.querySelector('#appSettings53').hidden=true;test52.openProfile('user')});assert.equal(await page.locator('#profileUI>header [data-background59=profile]').count(),0);await page.locator('#profileUI .profile-name button').click();assert.ok(await page.locator('#profileUI [data-background60=profile]').isVisible());await page.evaluate(()=>document.querySelector('#profileUI').hidden=true);results.push('v59 six public backgrounds, live preview, save/cancel and own profile entry');

 await page.evaluate(()=>{document.querySelector('#appSettings53').hidden=true;test52.openConversation(test52.active().id);test52.active().cfg.storyEffects56=true;test52.active().cfg.storyTextCap59=1;test59.story({text:'保留原来的角色性格',input:false,effects:['glow','textFill','binaryRain'],effectDuration:10,effectText:'还在这里',textTransform:{scale:.9,rotation:12},glow:{color:'#65aeff',intensity:.6,targets:['text','choices']},buttons:[{id:'one',label:'我爱你',glow:true,transform:{scale:1.1,rotation:0}}]})});
 assert.equal(await page.locator('.story51-controls button').count(),1);assert.ok(await page.locator('.story-transform59').first().evaluate(e=>e.style.transform.includes('12deg')));await page.waitForTimeout(550);assert.ok(await page.locator('.textFill59 span').count()>3);assert.ok(await page.locator('.binary-piece59').count()>0);assert.ok(await page.locator('.story51-controls button').evaluate(e=>getComputedStyle(e).boxShadow!=='none'));await shot('v59-story-glow-rain');assert.ok(await page.locator('.story51-exit').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth&&document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)===e}),'story exit must remain visible and clickable above effects');await page.waitForTimeout(700);assert.equal(await page.locator('.textFill59').count(),0);await page.evaluate(()=>test52.closeStory());assert.equal(await page.locator('.binary-piece59').count(),0);
 await page.evaluate(()=>test59.story({text:'文字掉落',effects:['textFall'],effectText:'接住我',buttons:[{id:'one',label:'继续'}]}));await page.waitForTimeout(500);assert.ok(await page.locator('.textFall59 span').count()>0);await page.evaluate(()=>test52.closeStory());
 await page.evaluate(()=>test59.survey());await page.waitForTimeout(500);assert.ok(await page.locator('.questionnaire58 .binary-piece59').count()>0);await shot('v59-question-rain');await page.getByRole('button',{name:'取消',exact:true}).last().click();await page.waitForTimeout(500);assert.equal(await page.locator('.binary-piece59').count(),0);results.push('v59 one choice, timed text cap/cleanup, text transforms, choice glow and binary rain in story/survey');

 await page.evaluate(async()=>{const p=test52.active();test52.openConversation(p.id);await test52.withRun(p,'你确定？',async()=>{const trace=test57.log(p,'查看作品评论','测试任务名称');test57.finish(p,trace,'success','实际评论内容')});test52.render()});assert.ok(await page.locator('.execution57 .muted57').last().textContent().then(t=>t.includes('查看作品评论')&&!t.includes('你确定？')));results.push('v59 execution task summary uses actual tools instead of the user question');
 await page.evaluate(async()=>{const original=window.qasNativeSend,calls=[],root=document.createElement('div');root.id='math-bridge59';root.style.cssText='font-size:20px;color:rgb(12,34,56)';document.body.append(root);window.qasNativeSend=async(action,args)=>{calls.push({action,args});return {data:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',width:40,height:24,baseline:.75,engine:'JLaTeXMath Android 0.2.0'}};try{test59.math(root,'\\frac{桥接59}{2}',false);test59.math(root,'\\frac{桥接59}{2}',false);await new Promise(r=>setTimeout(r,40));const images=root.querySelectorAll('.native-math59 img');if(calls.length!==1||calls[0].action!=='latexRender'||calls[0].args.color!=='#0c2238'||images.length!==2||root.firstChild.dataset.engine59!=='JLaTeXMath Android 0.2.0'||!root.firstChild.style.verticalAlign.startsWith('-'))throw Error('原生公式桥接、缓存或基线错误')}finally{window.qasNativeSend=original;root.remove()}});results.push('v59 Android formula bridge selects native images, caches a render and keeps inline baseline');
 await page.evaluate(()=>{const c=test52.active();c.cfg.size=180;test52.configure({size:180});c.messages.push({id:'voice-vector59',role:'assistant',type:'voice',content:'测试',duration:5,created:Date.now()});test52.render()});
 const glyph=await page.locator('.voice-play svg').last().boundingBox(),circle=await page.locator('.voice-play').last().boundingBox();assert.ok(glyph.width<circle.width&&glyph.height<circle.height);assert.ok(glyph.x>=circle.x&&glyph.x+glyph.width<=circle.x+circle.width+1);await shot('v59-voice');
 await page.evaluate(()=>{test52.configure({size:100});test52.beginSettings();test58.category('identity');document.querySelector('#settingsShade .settings-body58').scrollTop=400;test58.category('tools');test58.category('identity')});await page.waitForTimeout(260);assert.ok(await page.locator('#settingsShade .settings-body58').evaluate(e=>e.scrollTop>250));await page.setViewportSize({width:1100,height:850});await shot('v59-tablet-settings');
 await page.evaluate(()=>{test52.state.shared.reduceMotion52=true;test58.category('tools')});assert.equal(await page.locator('#settingsShade .settings-body58').evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length),0);await page.evaluate(()=>{test52.state.shared.reduceMotion52=false;test52.discard()});results.push('v59 bounded vector voice, settings scroll restoration, phone/tablet and reduced-motion navigation');
};
