const fs=require('node:fs'),path=require('node:path');
module.exports=async function verifyRework(page,assert,results){
 const review=path.resolve('ui-review');fs.mkdirSync(review,{recursive:true});
 const capture=async name=>{await page.waitForTimeout(300);for(const selector of ['#settingsShade.open','#settingsShade.open .panel'])if(await page.locator(selector).count())assert.ok(await page.locator(selector).evaluate(n=>Number(getComputedStyle(n).opacity)>.99),'settings animation failed to settle');await page.screenshot({path:path.join(review,name)})};
 const categories={identity:'cfgPrompt',connection:'cfgModel',conversation:'cfgSplit',proactive:'cfgProactive',memory:'cfgContextCompression',voice:'cfgTtsVoice',appearance:'cfgBgPreset',story:'allowHorror51',tools:'cfgExperimentalFiles',session:'clearCharacterMemory'};
 await page.evaluate(()=>{test52.openConversation(test52.active().id);test52.active().cfg.theme='light';test52.beginSettings()});
 assert.equal(await page.locator('#settingsIndex57 button.settings-row58').count(),10);
 for(const [key,id]of Object.entries(categories)){
  await page.evaluate(key=>test58.category(key),key);await page.locator('#'+id).scrollIntoViewIfNeeded();assert.ok(await page.locator('#'+id).isVisible(),'hidden '+key+' / '+id);
  const footer=await page.locator('.settings-footer58').boundingBox();assert.ok(footer&&footer.y+footer.height>870,'footer '+key);
  await page.evaluate(()=>test52.back());assert.ok(await page.locator('#settingsIndex57').isVisible(),'back '+key);
 }
 await page.evaluate(()=>test58.category('identity'));
 const oldName=await page.locator('#cfgName').inputValue();await page.locator('#cfgName').fill('取消不应留下这个名字');await page.locator('#cancelSettings').click();
 assert.equal(await page.evaluate(()=>test52.active().cfg.name),oldName);
 await page.evaluate(()=>test52.beginSettings());await page.evaluate(()=>test58.category('conversation'));await page.locator('#cfgSplit').setChecked(true);await page.locator('#saveSettings').click();await page.evaluate(()=>test52.beginSettings());await page.evaluate(()=>test58.category('conversation'));assert.ok(await page.locator('#cfgSplit').isChecked());await page.evaluate(()=>test52.discard());
 await page.evaluate(()=>{test52.state.shared.listTheme='dark';test52.openAppSettings()});await capture('settings-dark-phone.png');
 await page.locator('#appSettings53 button.settings-row58').filter({hasText:'通用显示'}).click();assert.ok(await page.locator('#cfgLanguage').isVisible());assert.ok(!(await page.locator('#cfgName').isVisible()));await page.evaluate(()=>test52.back());assert.ok(await page.locator('#appSettings53').isVisible());
 for(const [title,id]of [['回复与打断','cfgOutputMode'],['通知与声音','noticeSound'],['翻译服务','translationUrl'],['备份与恢复','exportData'],['开发者选项','devRequests']]){await page.locator('#appSettings53 button.settings-row58').filter({hasText:title}).click();await page.locator('#'+id).scrollIntoViewIfNeeded();assert.ok(await page.locator('#'+id).isVisible(),title);await page.locator('#cancelSettings').click();assert.ok(await page.locator('#appSettings53').isVisible())}
 await page.setViewportSize({width:1009,height:1500});await page.evaluate(()=>{document.querySelector('#appSettings53').hidden=true;test52.beginSettings()});await capture('role-settings-light-tablet.png');await page.evaluate(()=>test58.category('connection'));assert.ok(await page.locator('#cfgUrl').isVisible());await capture('role-model-tablet.png');await page.locator('#cancelSettings').click();
 await page.evaluate(()=>{const t=test52,v=test57;window.roleBeforeGroup58=t.active().id;const a=v.make('甲'),b=v.make('乙'),c=v.make('丙');t.state.conversations.push(a,b,c);const g=v.make('布局验证群','group',['user',a.id,b.id,c.id]);g.ownerId='user';t.state.conversations.push(g);window.groupUnderTest58=g.id;t.openConversation(g.id);t.beginSettings()});
 await page.locator('.group-settings58 button.settings-row58').filter({hasText:'成员与管理'}).click();assert.equal(await page.locator('.group-member58').count(),4);
 const rows=await page.locator('.group-member58').evaluateAll(nodes=>nodes.map(n=>{const buttons=[...n.querySelectorAll('button')].map(b=>b.getBoundingClientRect());return {height:n.getBoundingClientRect().height,gap:buttons.length>1?buttons[1].left-buttons[0].right:99}}));assert.ok(rows.every(r=>r.gap>=10&&r.height>=68));await capture('group-members-tablet.png');
 await page.locator('.group-member58 button').filter({hasText:'管理'}).first().click();await page.locator('#dialog button').filter({hasText:/^禁言$/}).click();assert.ok(await page.evaluate(()=>test52.active().mutedMembers.length===1));
 await page.evaluate(()=>test52.back());await page.locator('.group-settings58 button.settings-row58').filter({hasText:'消息与外观'}).click();assert.ok(await page.locator('.group-settings58 input[type=checkbox]').isVisible());await page.locator('.group-settings58 input[type=checkbox]').setChecked(false);assert.equal(await page.evaluate(()=>test52.active().showSender),false);await page.locator('.group-settings58>header button').click();assert.ok(await page.locator('.group-settings58 button.settings-row58').filter({hasText:'消息与外观'}).isVisible());await page.locator('.group-settings58>header button').click();assert.equal(await page.locator('.group-settings58').count(),0);await page.evaluate(()=>test52.openConversation(window.roleBeforeGroup58));
 results.push('explicit settings categories expose real controls, save/cancel and scoped return paths, phone/tablet grouped layouts and group management binding');

 await page.evaluate(async()=>{const t=test52,p=t.active(),other=test57.make('名片主人');t.state.conversations.push(other);const page=t.rolePage(other);page.name='名片主页';page.works=[{id:'work58',title:'真实作品',description:'作品正文',images:[{text:'文字作品'}],comments:5,commentEntries53:[{id:'comment58',authorId:other.id,text:'可读取的真实评论',likedBy:[]}]}];const card={id:'card58',role:'user',type:'contactCard',contact:{id:other.id,name:'名片主人',bio:'可读的签名',avatar:'data:image/png;base64,eA=='},content:'分享名片：名片主人',created:Date.now()};p.messages.push(card);const history=test58.history(p).find(m=>m.content.includes('[分享角色名片]'))?.content||'';if(!history.includes(other.id)||!history.includes('可读的签名')||!history.includes('不是用户发送的图片'))throw Error('名片上下文缺少真实身份或边界');const inspect={type:'inspectProfile',ownerId:other.id};if(!await t.tool(p,inspect))throw Error('主页工具失败 '+inspect._result);const data=JSON.parse(inspect._result);if(data.ownerId!==other.id||data.works[0].workId!=='work58')throw Error('读取了错误主页');const native='<｜DSML｜function_calls><｜DSML｜invoke name="readWorkComments"><｜DSML｜parameter name="ownerId" string="true">'+other.id+'</｜DSML｜parameter><｜DSML｜parameter name="workId" string="true">work58</｜DSML｜parameter></｜DSML｜invoke></｜DSML｜function_calls>';const actions=test58.parse(native);if(actions[0]?.type!=='readWorkComments')throw Error('有效原生评论工具被拒绝 '+JSON.stringify(actions));await t.actions(actions,p.id);const comments=JSON.parse(actions[0]._result);if(comments.ownerId!==other.id||comments.comments[0].text!=='可读取的真实评论'||comments.reportedComments!==5)throw Error('真实评论与统计未区分');const like={type:'likeWorkComment',ownerId:other.id,workId:'work58',commentId:'comment58'};if(!await t.tool(p,like)||!page.works[0].commentEntries53[0].likedBy.includes(p.roleId||p.id))throw Error('评论点赞未实际执行');const post={type:'postWorkComment',ownerId:other.id,workId:'work58',text:'新发布的真实评论'};if(!await t.tool(p,post)||page.works[0].comments!==6||!page.works[0].commentEntries53.some(c=>c.id===JSON.parse(post._result).commentId&&c.text===post.text))throw Error('评论发布未保留统计或真实正文');const bad={type:'postWorkComment',ownerId:other.id,workId:'wrong',text:'不应该发布'};if(await t.tool(p,bad)||!JSON.parse(bad._result).error.includes('作品不存在'))throw Error('失败被误报为成功');p.cfg.allowViewUserProfile=false;const denied={type:'inspectProfile',ownerId:'user'};if(await t.tool(p,denied)||!denied._result.includes('权限未开启'))throw Error('用户主页权限绕过');});
 results.push('name cards carry stable owner IDs, DSML comment tools execute, profile owner/work/comment IDs align, unavailable text and denied operations stay honest');

 await page.evaluate(()=>{const t=test52,p=t.active();p.cfg.horror51=true;p.cfg.storyEffects56=true;t.state.shared.reduceMotion52=false;const scene=test58.normalize({scene:{text:'氛围文本',palette:'light',effects:['mirror','rotate','noise','scanlines','digitalRain','cracks','invert'],intensity:.6}});if(scene.effects.length!==7||scene.palette!=='light')throw Error('剧情效果未归一化');const s=t.showStory(p,{scene:{...scene,revealDelay:0,input:false}},true);if(!s.root.querySelector('.atmosphere-digitalRain58')||s.root.querySelectorAll('.rain-column58').length!==20)throw Error('数字雨未出现');if(!s.root.querySelector('.story51-line').style.transform.includes('scaleX(-1)')||!s.root.querySelector('.story51-line').style.transform.includes('180deg'))throw Error('镜像倒转未保留');if(!test52.proto(p).includes('不假设用户理解')||!test52.proto(p).includes('突然换性格'))throw Error('剧情可读性/人设约束缺失');});
 await page.waitForTimeout(600);await capture('story-atmosphere-tablet.png');await page.locator('.story51-exit').click();assert.equal(await page.locator('.scene-atmosphere58,.rain-column58').count(),0);assert.ok(await page.evaluate(()=>![...document.body.children].some(n=>n.inert)));
 await page.evaluate(()=>{test58.popup({title:'问卷视觉验证',palette:'dark',questions:[{id:'q1',type:'single',label:'选择一项',required:true,options:['甲','乙']},{id:'q2',type:'textInput',label:'写下感受',required:true}]})});await page.locator('.questionnaire58 .interaction-options label').first().click();await page.locator('.questionnaire58 .interaction-fields input[type=text]').fill('真实作答');assert.equal(await page.locator('.questionnaire58 [role=progressbar]').getAttribute('aria-valuenow'),'2');await capture('questionnaire-dark-tablet.png');await page.locator('.global-interaction-shade header button').click();results.push('model-selected story effects preserve persona and unreadable-text rule, atmosphere cleanup leaves usable exit, questionnaire progress reflects actual answers');

 await page.evaluate(()=>{const t=test52;t.state.shared.firstLaunch53=true;window.beforeReplay58=JSON.stringify(t.copy(t.state));test52.openAppSettings();test52.firstLaunch(true)});await page.locator('.prank53 input').fill('不覆盖现有名称');await page.locator('.prank53 button').filter({hasText:'创建账号'}).click();assert.equal(await page.locator('.prank53 i').count(),44);const delays=await page.locator('.prank53 i').evaluateAll(ns=>ns.map(n=>getComputedStyle(n).animationDelay));assert.ok(delays.slice(1).every(d=>Number.parseFloat(d)<0));await page.waitForTimeout(3100);await page.locator('.prank53 button').filter({hasText:/^退出$/}).click();assert.ok(await page.locator('.prank53').evaluate(n=>n.classList.contains('leaving58')));await page.waitForTimeout(550);assert.equal(await page.locator('.prank53').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(test52.copy(test52.state))),await page.evaluate(()=>window.beforeReplay58));assert.ok(await page.locator('#appSettings53').isVisible());
 await page.setViewportSize({width:430,height:900});results.push('developer replay preserves data and first-use flag, continuous negative-delay confetti exits with a real transition and restores original page');
 await page.evaluate(()=>{document.querySelector('#appSettings53').hidden=true;test58.wallpaper('data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="purple"/></svg>'));test52.showMessages()});for(let i=0;i<3;i++){await page.evaluate(()=>{test52.showHome();test52.showMessages()});assert.equal(await page.locator('.list-wallpaper-image').evaluate(n=>getComputedStyle(n).filter),'blur(18px)');assert.equal(await page.locator('.list-row').first().evaluate(n=>getComputedStyle(n).backdropFilter),'none')}
 await capture('messages-stable-blur-phone.png');results.push('list wallpaper blur remains on a single layer through repeated navigation');
 await page.evaluate(()=>{test52.openConversation(test52.active().id);const t=test52,p=t.active();window.transfer58=test58.transfer({from:'user',to:p.id,cents:1,status:'returned',created:Date.now()});p.messages.push({id:'refund58',role:'user',type:'transferCard',transferId:window.transfer58.id,content:'退还',created:Date.now()});t.render()});
 // The fixture uses the same message type as the live transfer presenter.
 const refund=page.locator('.transfer-bubble.returned');assert.ok(await refund.count());assert.ok(await refund.textContent().then(s=>s.includes('¥0.01')&&s.includes('转账 · 已退还')));await capture('refund-card-phone.png');results.push('refund card keeps compact amount/status hierarchy and actual transfer state');
};
