const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
let pw;try{pw=require('playwright')}catch{pw=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')}
const root=path.resolve(__dirname,'..');
const hook=`window.test52={state,active,showHome,showMessages,leaveChat,openWorkflows:openWorkflows52,editWorkflow:editWorkflow52,startSelection,endSelection,configure(values){Object.assign(cfg,values);active().cfg=cfg},proto:compactActionProtocol,readDiary:readDiary512,tool:executeExtendedTool,actions:executeActions,render:renderMessages,openConversation,beginSettings,discard:discardSettings,incoming:onAiMessage,unknown:addUnknown52,threads:smsThreads,validate:validateWorkflow52,run:runWorkflow52,openFlows:openWorkflows52,input:inputAction52,back:back52,snapshot:snapshot52,openDiary,openProfile,musicEvent,get musicSession(){return listenSession},set musicSession(s){listenSession=s},get musicCharacter(){return musicCharacter()},setModel(fn){modelText=fn},idle:idleDiary52,openListen:()=>{$('#listenOverlay').hidden=false},get history(){return nav52},get browserBusy(){return browserBusy},generateBrowserHistory,notifyNative:notifyNative52,playTrack:playListenTrack,putMedia,audio:listenAudio};`;
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0].slice(1);if(!['index.html','update.js','android-runtime.js'].includes(name)){res.writeHead(404);return res.end()}let data=fs.readFileSync(path.join(root,name),'utf8');if(name==='index.html')data=data.replace('renderMemories();renderComposer();render();for(const c of state.conversations)',hook+'\nrenderMemories();renderComposer();render();for(const c of state.conversations)');res.setHeader('Content-Type',name.endsWith('html')?'text/html':'text/javascript');res.end(data)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw.chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH,args:['--no-sandbox']}:{} )});const page=await browser.newPage({viewport:{width:430,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.test52);await page.waitForTimeout(500);assert.deepEqual(errors,[]);
const results=await page.evaluate(async()=>{const t=test52,c=t.active();const checks=[];c.cfg.actionDescriptions=true;if(!t.proto(c).includes('actionDescription'))throw Error('动作权限未传入');checks.push('action switch');c.cfg.browserHistory=[{id:'b',text:'草东音乐',created:Date.now()-3600000}];const a={type:'readBrowserHistory',query:'草东'};await t.actions([a],c.id);if(JSON.parse(a._result).records.length!==1)throw Error('浏览读取');checks.push('browser retrieval');
t.beginSettings();const m={id:'testread',role:'assistant',type:'text',content:'设置中收到',created:Date.now()};c.messages.push(m);t.incoming(c,m);if(!m.readByUser||c.unread)throw Error('设置未读');t.discard();checks.push('settings read');
await new Promise(r=>setTimeout(r,100));c.cfg.smsUnknownAllowed=true;c.cfg.smsUnknownCount=3;for(let i=1;i<=3;i++)await t.unknown(c,i);let threads=[...t.threads.values()].filter(x=>x.characterId===c.id&&x.unknown&&!x.deleted);if(threads.length!==3)throw Error('未知多号');const id=threads[1].id;threads[1].deleted=true;await t.unknown(c,2);if(t.threads.get(id).deleted)throw Error('恢复号码');checks.push('multiple SMS identities');
t.configure({aiWriteDiary:true,proactive:false,url:'https://example.com',model:'test'});t.setModel(async()=>'{"diary":"今天聊过音乐。"}');await t.idle(c);if(!c.cfg.diaryEntries.at(-1)?.text.includes('音乐'))throw Error('独立日记');checks.push('idle diary without proactive DM');
const browsed=Date.now()-7200000;t.setModel(async()=>JSON.stringify({actions:[{op:'add',text:'时间测试一',created:browsed},{op:'add',text:'时间测试二'}]}));await t.generateBrowserHistory(c);const generated=c.cfg.browserHistory.filter(x=>x.text.startsWith('时间测试'));if(generated.length!==2||generated[0].created!==browsed||generated[0].created===generated[1].created)throw Error('浏览时间分布');checks.push('browsing time distinct from refresh');
let musicCalls=0,musicPrompt='';t.setModel(async(p,prompt)=>{musicCalls++;musicPrompt=prompt;return '{"actions":[{"type":"noReply"}]}'});t.musicSession={id:'music-test',characterId:c.id};t.musicEvent('暂停');t.musicEvent('换歌');await new Promise(r=>setTimeout(r,1450));if(musicCalls!==1||!musicPrompt.includes('暂停')||!musicPrompt.includes('换歌'))throw Error('音乐操作合并');t.musicSession=null;checks.push('music event aggregation');
const w=t.validate({name:'分支测试',nodes:[{id:'a',type:'role',text:'回答',next:'b'},{id:'b',type:'branch',contains:'yes',next:'c',otherwise:'d'},{id:'c',type:'message',text:'命中',next:'end'},{id:'d',type:'message',text:'未命中',next:'end'},{id:'end',type:'wait',seconds:0}]});t.setModel(async()=>'yes');const result=await t.run(w,c);if(!c.messages.some(x=>x.content==='命中')||c.messages.some(x=>x.content==='未命中'))throw Error('分支 '+JSON.stringify(result));checks.push('workflow branch and execution');
let rejected=false;try{t.validate({nodes:[{id:'a',type:'eval',text:'bad'}]})}catch{rejected=true}if(!rejected)throw Error('类型验证');checks.push('workflow validation');
const promise=t.input();document.querySelector('#dialog textarea').value='挥手';[...document.querySelectorAll('#dialog button')].find(b=>b.textContent==='确定').click();if(await promise!=='挥手')throw Error('动作输入');checks.push('internal action dialog');
c.messages.push({id:'textsize',role:'user',type:'text',content:'测试语音',created:Date.now()},{id:'voicesize',role:'user',type:'voice',content:'测试',duration:3,created:Date.now()});t.render();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const vb=document.querySelector('.bubble:has(>.voice-bubble)'),normal=[...document.querySelectorAll('.bubble')].find(x=>x.textContent==='测试语音');if(!vb||!normal||Math.abs(vb.getBoundingClientRect().height-normal.getBoundingClientRect().height)>2)throw Error('语音高度 '+vb?.getBoundingClientRect().height+' / '+normal?.getBoundingClientRect().height);checks.push('voice matches text height');return checks});
assert.deepEqual(errors,[]);
await page.evaluate(()=>{const b=document.createElement('button');b.id='navtest';b.textContent='查看主页';b.onclick=()=>test52.openProfile(test52.active().id);document.body.append(b)});await page.evaluate(()=>document.querySelector('#navtest').click());await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>test52.snapshot().visible.includes('profileUI')));await page.evaluate(()=>{const b=document.createElement('button');b.id='navdm';b.textContent='进入私信';b.onclick=()=>{document.querySelector('#profileUI').hidden=true;test52.openConversation(test52.active().id)};document.body.append(b)});await page.evaluate(()=>document.querySelector('#navdm').click());await page.waitForTimeout(250);await page.evaluate(()=>test52.back());assert.ok(await page.evaluate(()=>test52.snapshot().visible.includes('profileUI')));assert.deepEqual(errors,[]);results.push('profile-to-DM return path');

await page.evaluate(()=>{document.querySelector('#profileUI').hidden=true;test52.leaveChat();test52.showHome()});
for(const tab of ['homeTab','messagesTab','myTab','homeTab','messagesTab']){await page.click('#'+tab);await page.waitForTimeout(220);await page.evaluate(tab=>{const visible=id=>getComputedStyle(document.getElementById(id)).display!=='none';if(tab==='messagesTab'&&(visible('homeOverview')||!visible('conversationRows')))throw Error('消息页串层');if(tab==='homeTab'&&(!visible('homeOverview')||visible('conversationRows')))throw Error('首页串层');if(tab==='myTab'&&!visible('profileUI'))throw Error('我的页未显示');if(tab!=='myTab'){const footer=document.querySelector('.list-footer').getBoundingClientRect();if(footer.bottom<innerHeight-30)throw Error('底栏位置 '+footer.bottom)}},tab);if(tab==='myTab')await page.evaluate(()=>test52.back())}
results.push('root tabs visibility and bottom navigation');
await page.click('#homeTab');await page.waitForTimeout(220);for(let i=0;i<3;i++){await page.evaluate(()=>{const b=document.createElement('button');b.id='enterfeature53';b.textContent='日记';b.onclick=()=>document.querySelector('#diaryOverlay').hidden=false;document.body.append(b);b.click();b.remove()});await page.waitForTimeout(50);await page.evaluate(()=>test52.back());await page.waitForTimeout(50)}assert.equal(await page.evaluate(()=>test52.history.length),0);results.push('closed home entries not replayed');
await page.evaluate(async()=>{const t=test52,c=t.active();c.toolEvidence51=[{type:'listPlugins',result:'旧工具内容'}];c.resume13={writes:{old:'old'}};c.interruption13={text:'旧任务'};t.openConversation(c.id);t.beginSettings();document.querySelector('#clearCharacterMemory').click();[...document.querySelectorAll('#dialog button')].find(b=>b.textContent==='确认清除').click();await new Promise(r=>setTimeout(r,150));if(c.toolEvidence51||c.resume13||c.interruption13||c.messages.length)throw Error('旧记忆未清');t.discard();const a={type:'listMusicTracks'};await t.actions([a],c.id);if(!JSON.parse(a._result).playlists)throw Error('歌单默认权限');const b={type:'inspectMusicRoom'};await t.actions([b],c.id);if(JSON.parse(b._result).ok!==false||t.proto(c).includes('"type":"inspectMusicRoom"'))throw Error('未播放音乐权限');t.openWorkflows();[...document.querySelectorAll('#pluginBody button')].find(b=>b.textContent==='新建工作流').click();if(document.querySelector('#pluginBody').textContent.includes('步骤编号'))throw Error('需要手填编号');if(!document.querySelector('#pluginBody select'))throw Error('缺少编辑器')});results.push('clear tool memory, music permissions and no-code workflow editor');
const native=await browser.newPage();const nativeErrors=[];native.on('pageerror',e=>nativeErrors.push(e.message));await native.addInitScript(()=>{window.nativeCalls=[];window.QasNative={postMessage(raw){const m=JSON.parse(raw);nativeCalls.push(m);queueMicrotask(()=>QasNative.onmessage({data:JSON.stringify({id:m.id,...(m.action==='settings'?{background:false}:{})})}))}}});await native.goto('http://127.0.0.1:'+server.address().port);await native.waitForFunction(()=>!!window.test52);await native.evaluate(async()=>{const t=test52,c=t.active();c.cfg.avatar='data:image/svg+xml;base64,'+btoa('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>');await t.notifyNative(c,{content:'你好'});if(!nativeCalls.some(x=>x.action==='notify'&&x.conversationId===c.id&&x.avatar.startsWith('data:image/')))throw Error('通知头像');t.state.shared.listenTracks=[{id:'song-test',name:'测试音乐',artist:'测试歌手'}];await t.putMedia('song-test',new Blob([new Uint8Array(1000)],{type:'audio/wav'}));await t.playTrack(0);if(!nativeCalls.some(x=>x.action==='musicLoad'&&x.title==='测试音乐')||!nativeCalls.some(x=>x.action==='musicChunk'))throw Error('原生音频传输');window.qasMediaState52(1000,3000,true);if(t.audio.paused||t.audio.currentTime!==1)throw Error('播放状态同步');c.cfg.inspectMusicRoom=true;t.musicSession={characterId:c.id};const action={type:'inspectMusicRoom'};await t.actions([action],c.id);const info=JSON.parse(action._result);if(info.song!=='测试音乐'||info.people!==2||!info.secondPerson)throw Error('当前音乐与第二人');t.audio.pause();const denied={type:'inspectMusicRoom'};await t.actions([denied],c.id);if(JSON.parse(denied._result).ok!==false)throw Error('暂停后权限');});assert.deepEqual(nativeErrors,[]);results.push('native avatar notification and chunked music/state bridge');
console.log('PASS',results.join(', '));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
