const assert=require('node:assert/strict'),fs=require('node:fs');const u=require('../update.js'),v=require('../version.json');
assert.equal(u.compare('V46','51-3'),-1);assert.equal(u.compare('51-3','51-3'),0);assert.equal(u.compare('51-10','51-3'),1);assert.equal(u.compare('51.3.0','51-3'),0);assert.throws(()=>u.compare('garbage','51-3'));
assert.equal(u.resolve(v).comparison,0);assert.equal(u.resolve({...v,version:String(Number(v.version)+1)}).comparison,1);
assert.equal(u.resolve(v,{versionCode:v.android.versionCode,versionName:v.android.versionName}).comparison,0);
assert.equal(u.resolve(v,{versionCode:v.android.versionCode-1,versionName:'older'}).downloadUrl,v.android.downloadUrl);
assert.throws(()=>u.resolve({...v,version:String(Number(v.version)+1),downloadUrl:'javascript:alert(1)'}));assert.throws(()=>u.resolve({...v,android:null},{versionCode:1}));
assert.match(fs.readFileSync('index.html','utf8'),/<title>QasDM v58<\/title>/);assert.equal(v.version,u.CURRENT_VERSION);assert.match(fs.readFileSync('android-runtime.js','utf8'),new RegExp('versionCode:'+v.android.versionCode));
(async()=>{assert.equal((await u.check(async()=>({ok:true,json:async()=>v}))).comparison,0);await assert.rejects(u.check(async()=>({ok:false,status:503})),/503/);await assert.rejects(u.check(async()=>({ok:true,json:async()=>{throw Error('Invalid JSON')}})),/Invalid JSON/);let attempts=0;const fallback=await u.check(async()=>{if(++attempts===1)throw Error('Failed to fetch');return {ok:true,json:async()=>({encoding:'base64',content:Buffer.from(JSON.stringify(v)).toString('base64')})}});assert.equal(attempts,2);assert.equal(fallback.notes,v.notes);console.log('PASS version comparison, platform downloads, validation, HTTP and JSON errors, packaged version consistency')})().catch(e=>{console.error(e);process.exitCode=1});

